// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWXFfbPWRlb2gwMtX-w6L9QhrKJZ-2uJg',
    appId: '1:1052735402009:web:0bcd12431640976f147a88',
    messagingSenderId: '1052735402009',
    projectId: 'escala-msg',
    authDomain: 'escala-msg.firebaseapp.com',
    storageBucket: 'escala-msg.firebasestorage.app',
    measurementId: 'G-EL1LDD5DZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdclEsDj2ox6Q1Q2sNI1ifBjtM-7k8TQ',
    appId: '1:1052735402009:android:dcadb49c72be4baa147a88',
    messagingSenderId: '1052735402009',
    projectId: 'escala-msg',
    storageBucket: 'escala-msg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaL9sPzKyCSMYUnHnxF4qv046R5TMAAXQ',
    appId: '1:1052735402009:ios:9596545466ffddc4147a88',
    messagingSenderId: '1052735402009',
    projectId: 'escala-msg',
    storageBucket: 'escala-msg.firebasestorage.app',
    iosBundleId: 'com.example.escalaMissa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaL9sPzKyCSMYUnHnxF4qv046R5TMAAXQ',
    appId: '1:1052735402009:ios:9596545466ffddc4147a88',
    messagingSenderId: '1052735402009',
    projectId: 'escala-msg',
    storageBucket: 'escala-msg.firebasestorage.app',
    iosBundleId: 'com.example.escalaMissa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWXFfbPWRlb2gwMtX-w6L9QhrKJZ-2uJg',
    appId: '1:1052735402009:web:0bcd12431640976f147a88',
    messagingSenderId: '1052735402009',
    projectId: 'escala-msg',
    authDomain: 'escala-msg.firebaseapp.com',
    storageBucket: 'escala-msg.firebasestorage.app',
    measurementId: 'G-EL1LDD5DZ6',
  );
}
